apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deploy
  labels:
    app: {{ .Values.configlabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.configlabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.configlabel }}
    spec:
      containers:
        - name: config-service
          image: {{ .Values.configimage }}
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-svc
spec:
  selector:
    app: {{ .Values.configlabel }}
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888