#define deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flippiapi-deploy
  labels:
    app: flippyapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flippyapi
  template:
    metadata:
      labels:
        app: flippyapi
    spec:
      containers:
        - name: flippy-api
          image: {{ .Values.flippyimage }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: flippy-configmap
                  key: config_url
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: flippy-configmap
                  key: registry_url
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: flippy-configmap
                  key: kafka_url
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: flippy-configmap
                  key: mongo_url
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value:  "admin"
            - name: MONGO_PASSWORD
              value: "password"
            - name: MONGO_DATABASE
              value: "orderdb"
            - name: JWT_HEAD
              value: "Authorization"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
---
apiVersion: v1
kind: Service
metadata:
  name: flippyapi-svc
spec:
  #type: NodePort
  selector:
    app: flippyapi
  ports:
    - protocol: TCP
      #protocol: TCP
      port: 9000
      targetPort: 9000
      #nodePort: 30008