apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deploy
  labels:
    app: flippy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flippy
  template:
    metadata:
      labels:
        app: flippy
    spec:
      containers:
        - name: registry-service
          image: {{ .Values.serviceimage }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: spring.cloud.config.uri
              value: "http://config-svc:8888/"
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: registry-svc
spec:
  type: NodePort
  selector:
    app: flippy
  ports:
    - nodePort: 30008
      port: 8761
      targetPort: 8761