apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deploy
  labels:
    app: shopapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shopapi
  template:
    metadata:
      labels:
        app: shopapi
    spec:
      containers:
        - name: shopapi
          image: {{ .Values.shopimage }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9010
          env:
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: foody-configmap
                  key: config_url
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: foody-configmap
                  key: registry_url
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: foody-configmap
                  key: kafka_url
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: foody-configmap
                  key: mongo_url
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value:  "admin"
            - name: MONGO_PASSWORD
              value: "password"
            - name: MONGO_DATABASE
              value: "orderdb"
            - name: JWT_HEAD
              value: "Authorization"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
---
apiVersion: v1
kind: Service
metadata:
  name: shopapi-svc
spec:
  type: NodePort
  selector:
    app: shopapi
  ports:
    - nodePort: 30010
      port: 9010
      targetPort: 9010